/*
 * Copyright 2011 Sebastian Köhler <sebkoehler@whoami.org.uk>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package uk.org.whoami.easyban.datasource;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.HashMap;
import org.bukkit.plugin.java.JavaPlugin;
import org.hsqldb.types.Types;
import uk.org.whoami.easyban.ConsoleLogger;
import uk.org.whoami.easyban.util.Subnet;

public class SQLDataSource implements DataSource {

    private Connection con;

    public SQLDataSource(JavaPlugin plugin) throws SQLException,
                                                   ClassNotFoundException {
        Class.forName("org.hsqldb.jdbc.JDBCDriver");
        ConsoleLogger.info("HSQLDB driver loaded");
        String path = plugin.getDataFolder().getAbsolutePath() + "/bans";
        con = DriverManager.getConnection("jdbc:hsqldb:file:" + path, "SA", "");
        ConsoleLogger.info("Connected to Database");
        setup();
        ConsoleLogger.info("Database setup finished");
    }

    private synchronized void setup() throws SQLException {
        ConsoleLogger.info("Setup");

        Statement st = con.createStatement();
        st.executeUpdate("CREATE TABLE IF NOT EXISTS player ("
                         + "player_id INTEGER GENERATED BY DEFAULT AS IDENTITY,"
                         + "player VARCHAR(20) NOT NULL,"
                         + "CONSTRAINT player_const_prim PRIMARY KEY (player_id),"
                         + "CONSTRAINT player_const_uniq UNIQUE(player)"
                         + ");");
        st.executeUpdate("CREATE TABLE IF NOT EXISTS ip ("
                         + "ip_id INTEGER GENERATED BY DEFAULT AS IDENTITY,"
                         + "player_id INTEGER NOT NULL,"
                         + "ip VARCHAR(40) NOT NULL,"
                         + "CONSTRAINT ip_const_prim PRIMARY KEY (ip_id),"
                         + "CONSTRAINT ip_const_ref FOREIGN KEY (player_id) REFERENCES player (player_id)"
                         + ");");
        st.executeUpdate("CREATE TABLE IF NOT EXISTS player_ban ("
                         + "player_ban_id INTEGER GENERATED BY DEFAULT AS IDENTITY,"
                         + "player_id INTEGER NOT NULL,"
                         + "admin VARCHAR(20) NOT NULL,"
                         + "reason VARCHAR(100),"
                         + "until TIMESTAMP,"
                         + "CONSTRAINT player_ban_const_prim PRIMARY KEY (player_ban_id),"
                         + "CONSTRAINT player_ban_const_uniq UNIQUE (player_id),"
                         + "CONSTRAINT player_ban_const_ref FOREIGN KEY (player_id) REFERENCES player (player_id)"
                         + ");");
        st.executeUpdate("CREATE TABLE IF NOT EXISTS subnet_ban ("
                         + "subnet_ban_id INTEGER GENERATED BY DEFAULT AS IDENTITY,"
                         + "subnet VARCHAR(100) NOT NULL,"
                         + "admin VARCHAR(20) NOT NULL,"
                         + "reason VARCHAR(100),"
                         + "CONSTRAINT subnet_ban_const_prim PRIMARY KEY (subnet_ban_id),"
                         + "CONSTRAINT subnet_ban_const_uniq UNIQUE (subnet)"
                         + ");");
        st.executeUpdate("CREATE TABLE IF NOT EXISTS country_ban ("
                         + "country_ban_id INTEGER GENERATED BY DEFAULT AS IDENTITY,"
                         + "country VARCHAR(2) NOT NULL,"
                         + "CONSTRAINT country_ban_const_prim PRIMARY KEY (country_ban_id),"
                         + "CONSTRAINT country_ban_const_uniq UNIQUE (country)"
                         + ");");
        st.executeUpdate("CREATE TABLE IF NOT EXISTS whitelist ("
                         + "whitelist_id INTEGER GENERATED BY DEFAULT AS IDENTITY,"
                         + "player_id INTEGER NOT NULL,"
                         + "CONSTRAINT whitelist_const_prim PRIMARY KEY (whitelist_id),"
                         + "CONSTRAINT whitelist_const_ref FOREIGN KEY (player_id) REFERENCES player (player_id)"
                         + ");");
    }

    private synchronized void createNick(String nick) throws SQLException {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "SELECT player FROM player WHERE player=?");
            pst.setString(1, nick);
            if(!pst.executeQuery().next()) {
                pst.close();
                pst = con.prepareStatement(
                        "INSERT INTO player (player) VALUES(?);");
                pst.setString(1, nick);
                pst.executeUpdate();
            }
        } catch(SQLException ex) {
            throw new SQLException(ex);
        }
    }

    @Override
    public synchronized void addIpToHistory(String nick, String ip) {
        PreparedStatement pst = null;
        try {
            createNick(nick);
            pst = con.prepareStatement(
                    "SELECT ip FROM ip WHERE"
                    + " player_id=(SELECT player_id FROM player WHERE player= ?) AND ip=?;");
            pst.setString(1, nick);
            pst.setString(2, ip);
            if(!pst.executeQuery().next()) {
                pst.close();
                pst = con.prepareStatement("INSERT INTO ip (player_id,ip) VALUES("
                                           + "(SELECT player_id FROM player WHERE player= ? ),"
                                           + "?"
                                           + ");");
                pst.setString(1, nick);
                pst.setString(2, ip);
                pst.executeUpdate();
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }

    @Override
    public synchronized void banNick(String nick, String admin, String reason,
            Long until) {
        PreparedStatement pst = null;
        try {
            createNick(nick);
            pst = con.prepareStatement("INSERT INTO player_ban (player_id,admin,reason,until) VALUES("
                                       + "(SELECT player_id FROM player WHERE player= ? ),"
                                       + "?,"
                                       + "?,"
                                       + "?"
                                       + ");");
            pst.setString(1, nick);
            pst.setString(2, admin);
            if(reason != null) {
                pst.setString(3, reason);
            } else {
                pst.setNull(3, Types.VARCHAR);
            }
            if(until != null) {
                pst.setTimestamp(4, new Timestamp(until));
            } else {
                pst.setNull(4, Types.TIMESTAMP);
            }
            pst.executeUpdate();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }

    @Override
    public synchronized void unbanNick(String nick) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "DELETE FROM player_ban WHERE "
                    + "player_id=(SELECT player_id FROM player WHERE player=?);");
            pst.setString(1, nick);
            pst.executeUpdate();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }

    @Override
    public synchronized void banSubnet(Subnet subnet, String admin,
            String reason) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement("INSERT INTO subnet_ban (subnet,admin,reason) VALUES("
                                       + "?,"
                                       + "?,"
                                       + "?"
                                       + ");");
            pst.setString(1, subnet.toString());
            pst.setString(2, admin);
            if(reason != null) {
                pst.setString(3, reason);
            } else {
                pst.setNull(3, Types.VARCHAR);
            }
            pst.executeUpdate();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }

    @Override
    public synchronized void unbanSubnet(Subnet subnet) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "DELETE FROM subnet_ban WHERE subnet=?;");
            pst.setString(1, subnet.toString());
            pst.executeUpdate();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }

    @Override
    public synchronized void banCountry(String code) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "INSERT INTO country_ban (country) VALUES(?);");
            pst.setString(1, code);
            pst.executeUpdate();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }

    @Override
    public synchronized void unbanCountry(String code) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "DELETE FROM country_ban WHERE country=?;");
            pst.setString(1, code);
            pst.executeUpdate();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }

    @Override
    public synchronized void whitelist(String nick) {
        PreparedStatement pst = null;
        try {
            createNick(nick);
            pst = con.prepareStatement("INSERT INTO whitelist (player_id) VALUES("
                                       + "SELECT player_id FROM player WHERE player=?"
                                       + ");");
            pst.setString(1, nick);
            pst.executeUpdate();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }

    @Override
    public synchronized void unWhitelist(String nick) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "DELETE FROM whitelist WHERE "
                    + "player_id=(SELECT player_id FROM player WHERE player=?);");
            pst.setString(1, nick);
            pst.executeUpdate();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }

    @Override
    public synchronized boolean isIpBanned(String ip) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "SELECT ip FROM ip WHERE player_id IN (SELECT player_id FROM player_ban) AND ip=?;");
            pst.setString(1, ip);
            return pst.executeQuery().next();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
            return false;
        }
    }

    @Override
    public synchronized boolean isSubnetBanned(String ip) {
        Statement st = null;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT subnet FROM subnet_ban;");
            while(rs.next()) {
                try {
                    Subnet sub = new Subnet(rs.getString(1));
                    if(sub.isIpInSubnet(InetAddress.getByName(ip))) {
                        return true;
                    }
                } catch(UnknownHostException ex) {
                }
            }
            return false;
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
            return false;
        }
    }

    @Override
    public synchronized boolean isNickBanned(String nick) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "SELECT player_id FROM player_ban WHERE player_id=(SELECT player_id FROM player WHERE player=?);");
            pst.setString(1, nick);
            return pst.executeQuery().next();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
            return false;
        }
    }

    @Override
    public synchronized boolean isCountryBanned(String code) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "SELECT country FROM country_ban WHERE country=?;");
            pst.setString(1, code);
            return pst.executeQuery().next();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
            return false;
        }
    }

    @Override
    public synchronized boolean isNickWhitelisted(String nick) {
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "SELECT player_id FROM whitelist WHERE player_id=(SELECT player_id FROM player WHERE player=?);");
            pst.setString(1, nick);
            return pst.executeQuery().next();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
            return false;
        }
    }

    @Override
    public synchronized String[] getHistory(String nick) {
        ArrayList<String> list = new ArrayList<String>();
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "SELECT ip FROM ip WHERE player_id=(SELECT player_id FROM player WHERE player=?);");
            pst.setString(1, nick);
            ResultSet rs = pst.executeQuery();
            while(rs.next()) {
                list.add(rs.getString(1));
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }

        return list.toArray(new String[0]);
    }

    @Override
    public synchronized String[] getBannedNicks() {
        ArrayList<String> list = new ArrayList<String>();
        Statement st = null;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(
                    "SELECT player FROM player WHERE player_id IN (SELECT player_id FROM player_ban);");
            while(rs.next()) {
                list.add(rs.getString(1));
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }

        return list.toArray(new String[0]);
    }

    @Override
    public synchronized String[] getBannedSubnets() {
        ArrayList<String> list = new ArrayList<String>();
        Statement st = null;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT subnet FROM subnet_ban;");
            while(rs.next()) {
                list.add(rs.getString(1));
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }

        return list.toArray(new String[0]);
    }

    @Override
    public synchronized String[] getBannedCountries() {
        ArrayList<String> list = new ArrayList<String>();
        Statement st = null;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT country FROM country_ban;");
            while(rs.next()) {
                list.add(rs.getString(1));
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }

        return list.toArray(new String[0]);
    }

    @Override
    public synchronized String[] getWhitelistedNicks() {
        ArrayList<String> list = new ArrayList<String>();
        Statement st = null;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(
                    "SELECT player FROM player WHERE player_id IN (SELECT player_id FROM whitelist);");
            while(rs.next()) {
                list.add(rs.getString(1));
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }

        return list.toArray(new String[0]);
    }

    @Override
    public synchronized String[] getNicks(String ip) {
        ArrayList<String> list = new ArrayList<String>();
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "SELECT player FROM player WHERE player_id IN (SELECT player_id FROM ip WHERE ip=?);");
            pst.setString(1, ip);
            ResultSet rs = pst.executeQuery();
            while(rs.next()) {
                list.add(rs.getString(1));
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }

        return list.toArray(new String[0]);
    }

    @Override
    public synchronized HashMap<String, Long> getTempBans() {
        HashMap<String, Long> map = new HashMap<String, Long>();
        Statement st = null;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(
                    "SELECT player,until FROM player_ban JOIN player ON player_ban.player_id=player.player_id WHERE until IS NOT NULL;");
            while(rs.next()) {
                map.put(rs.getString(1), rs.getTimestamp(2).getTime());
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }

        return map;
    }

    @Override
    public synchronized HashMap<String, String> getBanInformation(String nick) {
        HashMap<String, String> map = new HashMap<String, String>();
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "SELECT admin,reason,until FROM player_ban WHERE player_id=(SELECT player_id FROM player WHERE player=?);");
            pst.setString(1, nick);
            ResultSet rs = pst.executeQuery();
            while(rs.next()) {
                map.put("admin", rs.getString(1));
                if(rs.getString(2) != null) {
                    map.put("reason", rs.getString(2));
                }
                if(rs.getTimestamp(3) != null) {
                    map.put("until",
                            String.valueOf(rs.getTimestamp(3).getTime()));
                }
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }

        return map;
    }

    @Override
    public synchronized HashMap<String, String> getBanInformation(Subnet subnet) {
        HashMap<String, String> map = new HashMap<String, String>();
        PreparedStatement pst = null;
        try {
            pst = con.prepareStatement(
                    "SELECT admin,reason FROM subnet_ban WHERE subnet=?;");
            pst.setString(1, subnet.toString());
            ResultSet rs = pst.executeQuery();
            while(rs.next()) {
                map.put("admin", rs.getString(1));
                if(rs.getString(2) != null) {
                    map.put("reason", rs.getString(2));
                }
            }
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }

        return map;
    }

    @Override
    public synchronized void close() {
        try {
            Statement st = con.createStatement();
            st.execute("SHUTDOWN");
            con.close();
        } catch(SQLException ex) {
            ConsoleLogger.info(ex.getMessage());
        }
    }
}
